Algoritmo "Exercicio_Pag_46_1_H"
// Disciplina  : Lógica de Programação
// Professor   :Jailson Costa Dos Santos
// Descrição   : Um algoritmo que apresente o equivalente de 10 ate 100 graus celsius em farenheit
// Autor(a)    : João Victor Lima Dos Santos Manço
Var
// Seção de Declarações das variáveis 
 c,f : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
c<- 10

enquanto c < 101 faca
 f<- ((9 * c) + 160)/ 5
 escreval(f:1:2)
 c<- c +10
 fimenquanto


Fimalgoritmo